# Generated by Django 2.2.2 on 2019-09-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_requisition',
            old_name='phone_numner',
            new_name='phone_number',
        ),
    ]
