# Generated by Django 2.2.2 on 2019-09-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_request', '0002_auto_20190920_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_requisition',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
