# Generated by Django 2.2.2 on 2019-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_request', '0003_auto_20190920_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcil_cities',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='pcil_products',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
