# Generated by Django 2.2.2 on 2019-09-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_request', '0007_auto_20190920_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_requisition',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
